# Generated by Django 6.1.1 on 2026-10-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
