# Generated by Django 6.1.1 on 2026-10-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_membership_tenant_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='desciption',
            new_name='description',
        ),
    ]
