# Generated by Django 6.1 on 2026-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría, p. ej. "Ropa", "Accesorios".', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador amigable para URL, p. ej. "ropa".', max_length=120, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desmarcada, la categoría no se muestra.', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto.', max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador amigable para URL.', max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Detalle del producto mostrado en la tienda.', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto en la moneda de la tienda.', max_digits=10, verbose_name='Precio')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio tachado con fines promocionales (opcional).', max_digits=10, null=True, verbose_name='Precio anterior')),
                ('image', models.CharField(blank=True, help_text='URL de Cloudinary de la imagen principal del producto.', max_length=500, verbose_name='Imagen')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Existencias simples del producto. Sin control de inventario.', verbose_name='Cantidad disponible')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete: si está desmarcada, el producto se oculta pero sus pedidos se conservan.', verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='Si está marcado, se muestra en la sección destacada de la tienda.', verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece el producto.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
