# Generated by Django 6.1 on 2026-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent_wa', 'Enviado por WhatsApp'), ('confirmed', 'Confirmado'), ('fulfilled', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', help_text='Etapa del ciclo de vida del pedido.', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Suma de los productos sin envío ni descuentos.', max_digits=10, verbose_name='Subtotal')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío aplicado al pedido.', max_digits=10, verbose_name='Envío')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total del pedido (subtotal + envío).', max_digits=10, verbose_name='Total')),
                ('shipping_address', models.TextField(blank=True, help_text='Dirección donde se entrega el pedido.', verbose_name='Dirección de envío')),
                ('notes', models.TextField(blank=True, help_text='Notas del cliente o del vendedor sobre el pedido.', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('customer', models.ForeignKey(help_text='Cliente que realizó el pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot del nombre al momento del pedido. No cambia aunque el producto se modifique.', max_length=200, verbose_name='Nombre del producto')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Unidades solicitadas de este producto.', verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot del precio del producto al momento del pedido.', max_digits=10, verbose_name='Precio unitario')),
                ('order', models.ForeignKey(help_text='Pedido al que pertenece la línea.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(help_text='Producto referenciado. Puede quedar nulo si se elimina el producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
    ]
