# Generated by Django 6.1 on 2026-08-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente.', max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(help_text='Número en formato E.164, p. ej. +50212345678. Contacto de WhatsApp.', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo del cliente (opcional).', max_length=254, verbose_name='Correo electrónico')),
                ('address', models.TextField(blank=True, help_text='Dirección de entrega (opcional).', verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, help_text='Notas internas del vendedor sobre el cliente.', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
