# Generated by Django 6.1 on 2026-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash_on_delivery', 'Contra entrega'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='other', help_text='Forma en la que se pagará o se pagó el pedido.', max_length=20, verbose_name='Método')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('refunded', 'Reembolsado')], default='pending', help_text='Seguimiento simple del pago.', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto pagado o por pagar.', max_digits=10, verbose_name='Monto')),
                ('transaction_id', models.CharField(blank=True, help_text='Referencia externa, p. ej. número de boleta o transferencia.', max_length=100, verbose_name='Referencia')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Cuándo se confirmó el pago.', null=True, verbose_name='Fecha de pago')),
                ('order', models.OneToOneField(help_text='Pedido al que corresponde el pago.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
