# Generated by Django 6.1 on 2026-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(help_text='Nombre que se muestra públicamente en la tienda.', max_length=100, verbose_name='Nombre comercial')),
                ('description', models.TextField(blank=True, help_text='Descripción corta de la tienda para la landing.', verbose_name='Descripción')),
                ('logo', models.CharField(blank=True, help_text='URL de Cloudinary del logo de la tienda.', max_length=500, verbose_name='Logo')),
                ('whatsapp_number', models.CharField(help_text='Número en formato E.164, p. ej. +50212345678. Destino de los pedidos.', max_length=20, verbose_name='WhatsApp')),
                ('currency', models.CharField(default='GTQ', help_text='Código ISO 4217 de la moneda, p. ej. GTQ, USD, MXN.', max_length=3, verbose_name='Moneda')),
                ('primary_color', models.CharField(blank=True, help_text='Color de marca en formato HEX, p. ej. #FF5722.', max_length=7, verbose_name='Color principal')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desmarcada, la tienda no es visible públicamente.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tenant', models.OneToOneField(help_text='Tienda (Tenant) a la que pertenece este perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Perfil de tienda',
                'verbose_name_plural': 'Perfiles de tienda',
            },
        ),
    ]
