# Generated by Django 6.1 on 2026-08-29 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo de la tienda almacenado en Cloudinary.', max_length=255, null=True, verbose_name='Logo de la tienda'),
        ),
    ]
